
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.mooncoder.model.analizer.syntax;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int COMA = 5;
  public static final int MONTO = 4;
  public static final int error = 1;
  public static final int APOSTADOR = 3;
  public static final int BREAKLINE = 6;
  public static final int CABALLO = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CABALLO",
  "APOSTADOR",
  "MONTO",
  "COMA",
  "BREAKLINE"
  };
}

